# Search
search: 
  enable: true
  service: hexo # google/hexo/algolia/azure/baidu
  # google 
  google_api_key:
  google_engine_id:
  # algolia
  algolia_app_id:
  algolia_api_key:
  algolia_index_name:
  # azure
  azure_service_name:
  azure_index_name:
  azure_query_key:
  # baidu
  baidu_api_id:

# friends link
links:
  - name: cpuwolf的博客
    url: http://blog.csdn.net/cpuwolf
  - name: X-Plane 11
    url: http://x-plane.vip/
  - name: cpuwolf Github
    url: https://github.com/cpuwolf/

# navigation menu
menu:
  - name: 主页
    slug: home
    url: /
  - name: 文档存档
    slug: archives
    url: /archives
  - name: 聊天室功能
    slug: chat
    url: /chat

# widgets
widgets:
  - about
  - links
  - categories
  - tagcloud

# Less
less:
  compress: true

# use url, not username
social:
- slug: github
  url: https://github.com/cpuwolf
- slug: csdn
  url: http://blog.csdn.net/cpuwolf
- slug: rss
	url: /atom.xml
