# Search
search: 
  enable: true
  service: baidu # google/hexo/algolia/azure/baidu
  # google 
  google_api_key:
  google_engine_id:
  # algolia
  algolia_app_id:
  algolia_api_key:
  algolia_index_name:
  # azure
  azure_service_name:
  azure_index_name:
  azure_query_key:
  # baidu
  baidu_api_id: 13826537042608078079

# friends link
links:
  - name: FAA机场SIDSTAR
    url: http://www.faa.gov/air_traffic/flight_info/aeronav/digital_products/dtpp/search/
  - name: 模拟飞行航路查询
    url: http://rfinder.asalink.net/free/
  - name: FAA飞行员手册
    url: http://www.faa.gov/regulations_policies/handbooks_manuals/aviation/pilot_handbook/
  - name: 真实航路查询
    url: http://www.fltplan.com/
  - name: LOWI机场说明
    url: https://www.vacc-austria.org/?page=content/chartlist&icao=LOWI
  - name: cpuwolf的博客
    url: http://blog.csdn.net/cpuwolf
  - name: X-Plane 11
    url: http://x-plane.vip/
  - name: cpuwolf Github
    url: https://github.com/cpuwolf/
  - name: bettersky
    url: http://bettersky.ga/
  - name: IXEG
    url: http://ixeg.net/
  - name: steptosky
    url: http://steptosky.com/
  - name: ND ART
    url: http://nd-art-and-technology.com/
  - name: X aviation
    url: http://www.x-aviation.com
  - name: Flight Factor
    url: http://flightfactor.aero/
  - name: JAR Design
    url: http://jardesign.org/
  - name: QPAC US
    url: http://www.qpac-us.com/
  - name: FlyJSim
    url: http://www.flyjsim.com/
  - name: X-Plane官方商店
    url: http://store.x-plane.org/
  - name: X-Plane forum
    url: http://forums.x-plane.org/
  - name: VFlyteAir
    url: http://www.vflyteair.com/
  - name: Dai Media
    url: http://www.dai-media.com/
  - name: beti-X
    url: http://beti-x.com/
  - name: Airfoillabs
    url: http://www.airfoillabs.com/
  - name: simheaven
    url: http://simheaven.com
  - name: Aerobask
    url: http://aerobask.com/
  - name: Joan PC
    url: http://x-plane.joanpc.com/
  - name: simcoders
    url: http://www.simcoders.com/
  - name: alpilotx
    url: http://www.alpilotx.net/
  - name: badbadwether
    url: http://www.badbadweather.com/
  - name: vskylab
    url: http://www.vskylabs.com/
  - name: Jrollon
    url: http://www.jrollon.com/CRJ.html

# navigation menu
menu:
  - name: 主页
    slug: home
    url: /
  - name: 文档存档
    slug: archives
    url: /archives
  - name: 聊天室功能
    slug: chat
    url: /chat

# widgets
widgets:
  - about
  - links
  - categories
  - tagcloud

# Less
less:
  compress: true

# use url, not username
social:
- slug: github
  url: https://github.com/cpuwolf
- slug: csdn
  url: http://blog.csdn.net/cpuwolf
- slug: rss
	url: /atom.xml
