# Search
search: 
  enable: true
  service: baidu # google/hexo/algolia/azure/baidu
  # google 
  google_api_key:
  google_engine_id:
  # algolia
  algolia_app_id:
  algolia_api_key:
  algolia_index_name:
  # azure
  azure_service_name:
  azure_index_name:
  azure_query_key:
  # baidu
  baidu_api_id: 13826537042608078079

# friends link
links:
  - name: XTouchDownRecorder官方网址
    url: https://x-plane.vip/xtdr/
  - name: ff777wingflexfix
    url: https://github.com/cpuwolf/pyff777wingflexfix/releases
  - name: 美国FAA机场进离场程序
    url: http://www.faa.gov/air_traffic/flight_info/aeronav/digital_products/dtpp/search/
  - name: 模拟飞行世界航路查询
    url: https://flightplandatabase.com/
  - name: 模拟飞行航路查询
    url: http://rfinder.asalink.net/free/
  - name: 美国FAA飞行员手册
    url: http://www.faa.gov/regulations_policies/handbooks_manuals/aviation/pilot_handbook/
  - name: 北美真实航路查询
    url: http://www.fltplan.com/
  - name: 真实航路天气查询
    url: https://www.ventusky.com/
  - name: 奥地利LOWI机场说明
    url: https://www.vacc-austria.org/?page=content/chartlist&icao=LOWI
  - name: 国泰航空虚拟航空
    url: http://cpava.org/
  - name: 语音控制副驾驶
    url: https://planecommand.com/
  - name: XPUIPC
    url: http://www.tosi-online.de/XPUIPC/
  - name: cpuwolf的博客
    url: http://blog.csdn.net/cpuwolf
  - name: Marginal AutoGate
    url: https://marginal.org.uk/x-planescenery/plugins.html
  - name: RuScenery
    url: http://ruscenery.x-air.ru/
  - name: bettersky cloud
    url: http://bettersky.ga/
  - name: IXEG 737
    url: http://ixeg.net/
  - name: steptosky FF B757
    url: http://steptosky.com/
  - name: ND ART
    url: http://nd-art-and-technology.com/
  - name: X aviation IXEG B737
    url: http://www.x-aviation.com
  - name: Flight Factor FF757 FF777
    url: http://flightfactor.aero/
  - name: JAR Design A320 A330
    url: http://jardesign.org/
  - name: QPAC US A320
    url: http://www.qpac-us.com/
  - name: FlyJSim B727 B737-200
    url: http://www.flyjsim.com/
  - name: X-Plane.org官方商店
    url: http://store.x-plane.org/
  - name: X-Plane 10/11世界最大论坛
    url: http://forums.x-plane.org/
  - name: VFlyteAir
    url: http://www.vflyteair.com/
  - name: Dai Media
    url: http://www.dai-media.com/
  - name: beti-X
    url: http://beti-x.com/
  - name: Airfoillabs C172
    url: http://www.airfoillabs.com/
  - name: simheaven 地景
    url: http://simheaven.com
  - name: OpenSceneryX 地景库
    url: https://www.opensceneryx.com/
  - name: Aerobask
    url: http://aerobask.com/
  - name: Joan PC实时天气插件
    url: http://x-plane.joanpc.com/
  - name: simcoders
    url: http://www.simcoders.com/
  - name: alpilotx
    url: http://www.alpilotx.net/
  - name: 实时世界坏天气机场
    url: http://www.badbadweather.com/
  - name: vskylab
    url: http://www.vskylabs.com/
  - name: Jrollon CRJ-200
    url: http://www.jrollon.com/CRJ.html
  - name: Classic Aircraft
    url: http://forjets.netfirms.com/

# navigation menu
menu:
  - name: 主页
    slug: home
    url: /
  - name: 文档存档
    slug: archives
    url: /archives
  - name: XTouchDownRecorder
    slug: landings
    url: /xtdr/

# widgets
widgets:
  - about
  - links
  - categories
  - tagcloud

# Less
less:
  compress: true

# use url, not username
social:
- slug: github
  url: https://github.com/cpuwolf
- slug: sina-weibo
  url: http://weibo.com/cpuwolf
- slug: rss
  url: /atom.xml
